version: '3.8'

services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:latest
    container_name: homeassistant
    restart: unless-stopped
    privileged: true
    network_mode: host
    environment:
      - TZ=Europe/Rome
    volumes:
      - /volume1/docker/homeassistant:/config
