services:
  semaphore:
    image: semaphoreui/semaphore:v2.19.7
    container_name: semaphore
    restart: unless-stopped
    user: root
    ports:
      - "3003:3000"
    environment:
      SEMAPHORE_DB_DIALECT: sqlite
      SEMAPHORE_DB_HOST: /etc/semaphore/database.sqlite
      SEMAPHORE_ADMIN: admin
      SEMAPHORE_ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      SEMAPHORE_ADMIN_NAME: Admin
      SEMAPHORE_ADMIN_EMAIL: admin@localhost
      SEMAPHORE_ACCESS_KEY_ENCRYPTION: ${ACCESS_KEY_ENCRYPTION}
      TZ: Europe/Rome
    volumes:
      - /volume1/docker/semaphore/data:/etc/semaphore
      - /volume1/docker/semaphore/playbooks:/tmp/semaphore/project_1:rw
